### ISSUE TITLE
When a map is used JSON serialization is wrong

### ISSUE THREAD

**Issue by tarelli** [emfjson/emfjson-jackson#74]
We have an ecore with one reference named "initialValue" that is a map, here is a screenshot of the ecore:
![screen shot 2015-12-09 at 15 07 52](https://cloud.githubusercontent.com/assets/81127/11688810/a599d1e2-9e86-11e5-8aca-72650d4cf1f9.png)

When such reference is serialized the following JSON is produced:

```
				"id": "g",
				"name": "g",
				"types": [{
					"$ref": "//@libraries.1/@types.2"
				}],
				"initialValues": {: {
```
The problem is the double :{ :{ the second colon is unexpected.
Uncaught SyntaxError: Unexpected token :

**Comment by tarelli** [comment]
@ghillairet do you have a tentative due date for 0.14? Trying to decide the best course of action around this, thanks!

**Comment by ghillairet** [comment]
The fix for this one will be in maven snapshot repository today or tomorrow.

For maps that don't have keys of type string the serialization will look like that
```json
{
  "eClass" : "http://www.emfjson.org/jackson/model#//ETypes",
  "values" : [ {
    "key" : {
      "eClass" : "http://www.emfjson.org/jackson/model#//Type",
      "name" : "t1"
    },
    "value" : {
      "eClass" : "http://www.emfjson.org/jackson/model#//Value",
      "value" : 1
    }
  }, {
    "key" : {
      "eClass" : "http://www.emfjson.org/jackson/model#//Type",
      "name" : "t2"
    },
    "value" : {
      "eClass" : "http://www.emfjson.org/jackson/model#//Value",
      "value" : 2
    }
  } ]
}
```

A map with keys being string is serialized like that

```json
{
  "eClass" : "http://www.emfjson.org/jackson/model#//ETypes",
  "values" : {
     "t1": 1,
     "t2": 2 
  }
}
```

**Comment by tarelli** [comment]
@ghillairet great, thanks Guillaume!

**Comment by tarelli** [comment]
@ghillairet hi Guillaume, any update on release 0.1.4? Thanks!

**Comment by ghillairet** [comment]
I won't have time before next week, due to the move to the organization I have to re-setup the build for the eclipse update site.

**Comment by tarelli** [comment]
@ghillairet let me know if there's anything I can do to help :)

**Comment by ghillairet** [comment]
0.14 has been released (https://github.com/emfjson/emfjson-jackson/releases/tag/0.14.0) and includes fix for this issue.

**Comment by tarelli** [comment]
@ghillairet if the key is not contained in the map should there be a reference instead of the whole object?

**Comment by ghillairet** [comment]
Yes you right, see https://github.com/emfjson/emfjson-jackson/issues/83
