### ISSUE TITLE
Support for jackson like annotations

### ISSUE THREAD

**Issue by ghillairet** [emfjson/emfjson-jackson#79]
Investigate addition of annotations, like in [jackson](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations). 

Annotations could be defined in the textual format xcore like below, and also in the standard XMI format.

``` xtend
annotation "JsonProperty" as JsonProperty

class User {
    @JsonProperty(value = "user_name")
    String name
}
```

We should list in this issue the relevant annotations that could be supported.

**Comment by ghillairet** [comment]
JsonProperty annotation does now also work on methods since 1.0.0-rc.1

```java
class TestB {

	@JsonProperty( value = "my_value" )
	String value

	@JsonProperty
	op String hello() {
		"World"
	}
}
```

will return 

```json
{
  "eClass": "http://www.emfjson.org/jackson/annotations#//TestB",
  "hello": "World"
}
```

**Comment by kchobantonov** [comment]
Should we assume that this option can be turned on and off per mapper ?

**Comment by ghillairet** [comment]
That is not at the moment something that can be turn off, if annotations are present in the ecore model, then the mapper will consider them.
