### ISSUE TITLE
attribute with null as value is not checked

### ISSUE THREAD

**Issue by ungeildodger** [emfjson/emfjson-jackson#81]
If a plain JSON is read like the following example:
```
"matches": [
{
"continent": {
"matchHighlights": [],
"value": "Europa"
},
"city": {
"matchHighlights": [],
"value": "Stuttgart"
},
"logo44x44rounded": "someUrl",
"rating": null,
"description": {
"matchHighlights": [],
"value": "some description"
}
]
}

```
The null that appears in rating is not checked and the deserialization stumbles and breaks.

The solution looks easy:

It looks like the following snippet would do the job if added to line 195 in the `EObjectDeserializer.readFeature` method
`
if (jp.getCurrentToken() == JsonToken.VALUE_NULL) {
				return;
			}
`

**Comment by ghillairet** [comment]
Thanks for the PR, it's been added to the 0.15 release.

**Comment by ungeildodger** [comment]
Thx, Is therefor the Bugfix available on your p2 updatesite?

**Comment by ghillairet** [comment]
It should be there now, release 0.15.0.

**Comment by ungeildodger** [comment]
It appears, that http://ghillairet.github.io/p2/ is not available. Are there some structural changes I'm not aware of?

**Comment by ghillairet** [comment]
Fixed now.
