### ISSUE TITLE
Need to change the ref field name ($ref) by option

### ISSUE THREAD

**Issue by Dufgui** [emfjson/emfjson-jackson#87]
Since some commit,  we cannot change the field name of a reference ($ref) and it's blocking for mongo usage ($ref is reserved by mongo)

**Comment by ghillairet** [comment]
Which version are you using? Do you use the source from master, it is not yet ready, and it is definetly something that will be possible to do.

**Comment by Dufgui** [comment]
I try the rc1. :)

**Comment by ghillairet** [comment]
This has been added in RC1, see this test for usage https://github.com/emfjson/emfjson-jackson/blob/master/src/test/java/org/emfjson/jackson/tests/custom/CustomSerializersTest.java#L160
