### ISSUE TITLE
EMapEntrySerializer must use EDataType in certain cases

### ISSUE THREAD

**Issue by hb91546** [emfjson/emfjson-jackson#88]
... perhaps all cases.  This may be a more general problem and may or may not be restricted to user defined EDataTypes.  In this case the "key" of the Map.Entry is a user defined EDataType.

The current implementations of EMapSerializer and EMapEntrySerializer do not have access to EStructuralFeature reference values which is critical to process the values correctly.

BeanSerializer(BeanSerializerBase).serializeFields(Object, JsonGenerator, SerializerProvider) line: 675 
BeanSerializer.serialize(Object, JsonGenerator, SerializerProvider) line: 157
DefaultSerializerProvider$Impl(DefaultSerializerProvider).serializeValue(JsonGenerator, Object) line: 130
ObjectMapper.writeValue(JsonGenerator, Object) line: 2374
UTF8JsonGenerator(GeneratorBase).writeObject(Object) line: 324  
UTF8JsonGenerator(JsonGenerator).writeObjectField(String, Object) line: 1415
EMapEntrySerializer.serialize(Map$Entry, JsonGenerator, SerializerProvider) line: 29

```
    Here EMapEntrySerializer somehow must use the EDataType of Map.Entry key and value to serialize
    as we see here with XMIHelperImpl that uses the client’s generated
    factoryImpl convertToString method. 
        ClientEMFModelFactoryImpl.convertToString(EDataType, Object) line: 105  
            line: 105   the Object is an instance of the "key"

        XMIHelperImpl(XMLHelperImpl).updateQNamePrefix(EFactory, EDataType, Object, boolean) line: 1723 
        XMIHelperImpl(XMLHelperImpl).convertToString(EFactory, EDataType, Object) line: 1607    
            line: 1607 this is the EDataType of the feature

        XMISaveImpl(XMLSaveImpl).getDatatypeValue(Object, EStructuralFeature, boolean) line: 3108
            line: 3108  Object feature is "key" instance

        XMISaveImpl(XMLSaveImpl).saveDataTypeSingle(EObject, EStructuralFeature) line: 1698 
        XMISaveImpl(XMLSaveImpl).saveFeatures(EObject, boolean) line: 1280  
            line: 1280  The EObject feature is "key" to the Map.Entry

        XMISaveImpl(XMLSaveImpl).saveFeatures(EObject) line: 1224           
        XMISaveImpl(XMLSaveImpl).saveElementID(EObject) line: 2716  
                id  null    
        XMISaveImpl(XMLSaveImpl).saveElement(EObject, EStructuralFeature) line: 1181    
            line 1181:  the EObject is a Map.Entry, the feature EType instance class is Map.Entry   
                isAnyType   false   
                shouldSaveType  false   
                eDataType   null    

        XMISaveImpl(XMLSaveImpl).saveElement(InternalEObject, EStructuralFeature) line: 1042
        XMISaveImpl(XMLSaveImpl).saveContainedMany(EObject, EStructuralFeature) line: 2417
```

EMapEntrySerializer.serialize(Object, JsonGenerator, SerializerProvider) line: 1
DefaultSerializerProvider$Impl(DefaultSerializerProvider).serializeValue(JsonGenerator, Object) line: 130
ObjectMapper.writeValue(JsonGenerator, Object) line: 2374
UTF8JsonGenerator(GeneratorBase).writeObject(Object) line: 324  
EMapSerializer.serialize(EMap, JsonGenerator, SerializerProvider) line: 42
EObjectSerializer.serialize(EObject, JsonGenerator, SerializerProvider) line: 115
`The EObjectSerializer EReference has the information required to serialize properly the input EMap.`
`However, the reference is available in the EMapSerializer.`
EObjectSerializer.serialize(Object, JsonGenerator, SerializerProvider) line: 1
DefaultSerializerProvider$Impl(DefaultSerializerProvider).serializeValue(JsonGenerator, Object) line: 130
ObjectMapper.writeValue(JsonGenerator, Object) line: 2374   

I hope this helps.

**Comment by ghillairet** [comment]
Thanks for reporting this, I will look at it.

**Comment by ghillairet** [comment]
Should be fixed now
