### ISSUE TITLE
Support CDO lazy loading feature.

### ISSUE THREAD

**Issue by XingxiaoLu** [emfjson/emfjson-jackson#92]
CDO support lazy loading. How emfjson support this feature?

**Comment by ghillairet** [comment]
What kind of support would you like to see?

**Comment by XingxiaoLu** [comment]
The EObjectSerializer will traverse whole tree of the EObject.  This can not support the case of big data.

**Comment by ghillairet** [comment]
What is your use case? If you want to serialize a CDOResource you will have to traverse the whole tree anyway. What you can do is serialize only the objects you want, but this is handle by your application.
