### ISSUE TITLE
Link to the p2 repo is not working

### ISSUE THREAD

**Issue by peterkir** [emfjson/emfjson-jackson#97]
Link to p2 repo [http://ghillairet.github.io/p2](http://ghillairet.github.io/p2) on landing page is not working.

**Comment by ghillairet** [comment]
Do you mean install emfjson from this link does not work? 
This link does not point to any web page but to an eclipse update site, it should only be used in the eclipse update manager.

**Comment by jfaltermeier** [comment]
I am using the repository in a target definition file. I get this error:

Failed to load p2 metadata repository from location http://ghillairet.github.io/p2: Unable to read repository at http://ghillairet.github.io/p2. No repository found at http://ghillairet.github.io/p2/releases/emftriple/1.0.0.

I guess there is something wrong with the composite update site.

**Comment by ghillairet** [comment]
Should be fixed now.
